import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <head>
        <style>{`
          .container {
            width: 100%;
            margin: 0 auto;
            padding-bottom: 20px;
          }

          .title {
            text-align: center;
            padding: 10px;
          }

          .title h1 {
            font-size: 40px;
            margin: 0;
            padding: 0;
          }

          .titleItems,
          .items {
            display: grid;
            grid-template-columns: 2fr 1fr 1fr 1fr 1fr 1fr;
          }

          .titleItem {
            flex: 1;
          }

          .center {
            text-align: center;
          }

          .titleItems {
            border-bottom: 1px solid #000000;
            border-right: 1px solid #356854;
            background-color: #356854;
            color: #ffffff;
            font-family: docs-Roboto, Arial;
            font-size: 12px;
            padding: 10px 5px;
          }

          .item {
            border-bottom: 1px solid #000000;
            border-right: 1px solid #000000;
            border-left: 1px solid #000000;
            color: #434343;
            font-family: docs-Roboto, Arial;
            font-size: 12px;
            padding: 10px 5px;
          }

          .vendido {
            background-color: #34a853;
            color: #ffffff;
            font-family: docs-Roboto, Arial;
            font-size: 12px;
          }

          .items:nth-child(odd) {
            background-color: #f6f8f9;
          }
        `}</style>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
